sudo: required
language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
install:
  - npm install
before_script:
  - git config --global user.email "engineers@slotnslot.com"
  - git config --global user.name "Travis CI"
  - chmod +x ./scripts/travisBuild.sh
script: ./scripts/travisBuild.sh
after_script:
  - sh 'git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/SlotNSlot/SlotNSlot.git --tags -f'
